#!/bin/sh

lb config noauto \
  --mode debian \
  --distribution trixie \
  --debian-installer none \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live quiet splash toram" \
  --linux-flavours amd64 \
  --parent-archive-areas "main contrib non-free non-free-firmware" \
  --parent-mirror-bootstrap "http://deb.debian.org/debian/" \
  --parent-mirror-chroot    "http://deb.debian.org/debian/" \
  --parent-mirror-binary    "http://deb.debian.org/debian/" \
  --parent-mirror-chroot-security "http://security.debian.org/debian-security" \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian/" \
  --mirror-chroot    "http://deb.debian.org/debian/" \
  --mirror-binary    "http://deb.debian.org/debian/" \
  --mirror-chroot-security "http://security.debian.org/debian-security"

